name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Debug Runner
        shell: cmd
        run: |
          echo ==== PATH ====
          echo %PATH%
          echo.
          echo ==== JAVA ====
          where java
          java -version
          echo.
          echo ==== SONAR ====
          where sonar-scanner
          dir C:\tools\sonar-scanner-8.0.1.6346-windows-x64\bin

      - name: Run SonarScanner
        shell: cmd
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner ^
          -Dsonar.projectKey=demo-project ^
          -Dsonar.sources=. ^
          -Dsonar.host.url=%SONAR_HOST_URL% ^
          -Dsonar.token=%SONAR_TOKEN%
